# Drive the PACKAGECONFIG rules for wolfssl in all of it's varietals from the layer.conf, 
# local.conf, distro.conf here or in their respective places using the weak assignment in
# our local.conf to actually create it in the configure scope to be used everywhere.
PACKAGECONFIG_append_pn-wolfssl = "${WOLFSSL_PACKAGES}"
PACKAGECONFIG_append_pn-wolfssl-fips = "${WOLFSSL_PACKAGES}"
PACKAGECONFIG_append_pn-wolfssl-fips-ready = "${WOLFSSL_PACKAGES}"
